language: go

env:
  - GO111MODULE=on
  - PACKAGES=$(go list ./... | grep -v /examples/)

go:
  - 1.12.x

git:
  depth: 1

matrix:
  fast_finish: true

before_install:
  - go get github.com/mgechev/revive

install:
  - go get -t -v $PACKAGES

script:
  - test -z "$(revive -config revive.toml $PACKAGES)"
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt $PACKAGES
  # - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
