language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x

git:
  depth: 1

matrix:
  fast_finish: true

before_install:
  - go get github.com/mgechev/revive

install:
  - go get -t -v ./...

script:
  - test -z "$(revive -config revive.toml ./...)"
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt ./...
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
