baseURL: https://docli.dev
languageCode: en-us
title: Docli
googleAnalytics: UA-135349489-1
theme: book
enableGitInfo: true
enableEmoji: true
disableKinds:
  - taxonomy
  - taxonomyTerm

params:
  bookEditPath: edit/master/docs/content
  bookMenuBundle: /menu
  bookRepo: https://github.com/celicoo/docli
  bookTheme: auto
  logo: /avatar.png
